### ISSUE TITLE
Currated NuGets not showing up in package manager

### ISSUE THREAD

**Issue by XanNava** [xoofx/UnityNuGet#178] opened 2023-02-19 21:45 UTC
Unity vs:2022.2.0b16.112.5806
Issue: When I go to "package manager -> My Registeries" I see a few NuGets that I installed previously using UnityNuGet but it isn't loading/showing the curated list.

I had it working previously, and am not sure if this is related to the caching issue that was happening on server side, but I made sure if is setup correctly in my manifest.json. I can try installing this on a fresh unity install next if needed.

**Comment by xoofx** [comment] 2023-02-20 07:19
Duplicate of #175

We tried to fix it this week-end and the server should be up again.

**Closed by xoofx** 2023-02-20 07:19 UTC
Labels: duplicate
